public label struct
hirosassa/zerodriver pull request #21
Opened 2021-12-28 16:21 UTC by po3rin

The type of the `label` struct is private. Therefore, it is not possible to add a label conditionally. 

When this request is merged, the following processing will be possible.

```go
labels := make([]zerodriver.LabelSouce, 0, 0)

// Conditional branch pattern
if useSpecialLabel() {
    labels = append(lebels, zerodriver.Label("x", "x"))
}

// Loop pattern
for k, v := range DefaultLabels{
    labels = append(lebels,  zerodriver.Label(k, v))
}

// pass []LabelSource to Label method.
logger.Info().Labels(...labels).Msg("labeled log")
```

## discuss

Because the name `Label` was duplicated, I renamed the label struct to `labelSource`. Do you have any other good names ?

2021-12-28 21:31 UTC, hirosassa requested changes
@po3rin Thanks for your PR. I added small change request. Please check.

2021-12-28 21:31 UTC, hirosassa commented on label.go
> +type LabelSource struct {
The name of struct looks good. Thanks

2021-12-28 21:31 UTC, hirosassa commented on label.go
>  // Labels takes label structs, filters the ones that have their key start with the
Please fix the comment as below

```suggestion
// Labels takes LabelSource structs, filters the ones that have their key start with the
```

2021-12-29 04:21 UTC, po3rin commented on label.go
>  // Labels takes label structs, filters the ones that have their key start with the
applied !!

2021-12-29 10:45 UTC, hirosassa commented
@po3rin Thanks for great contribution!

2021-12-29 10:49 UTC, merged